global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi_master'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'python_worker'
    static_configs:
      - targets: ['worker:8001']
      
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']